/**
 * Agent Types
 * Types for the K8s Ops Agent orchestration layer
 */

import type {
  ClusterSnapshot,
  CostAnalysisResult,
  ZombieDetectionResult,
  IstioTrafficAnalysisResult,
} from "../types.js";

// ============ Agent Request/Response Types ============

/**
 * Supported agent intents that can be requested
 */
export type AgentIntent =
  | "cluster-health-check"
  | "cost-optimization"
  | "zombie-detection"
  | "istio-analysis"
  | "full-cluster-report";

/**
 * Agent request - what the user wants to analyze
 */
export interface AgentRequest {
  /** The intent/goal of the analysis */
  intent: AgentIntent;
  /** Optional natural language query (for future LLM integration) */
  query?: string;
  /** Optional namespace filter */
  namespaces?: string[];
  /** Include Istio resources in analysis */
  includeIstio?: boolean;
  /** Custom thresholds for analysis */
  thresholds?: {
    nodeUtilizationLow?: number;
    workloadOverprovisionRatio?: number;
    idlePodThresholdHours?: number;
    idleDaysThreshold?: number;
    crashLoopRestartThreshold?: number;
  };
}

/**
 * Individual step in the agent execution
 */
export interface AgentStep {
  /** Step number */
  stepNumber: number;
  /** Tool that was called */
  toolId: string;
  /** Status of the step */
  status: "pending" | "running" | "success" | "error";
  /** Start time */
  startedAt?: string;
  /** End time */
  completedAt?: string;
  /** Execution time in ms */
  durationMs?: number;
  /** Error if failed */
  error?: string;
}

/**
 * Findings from the analysis - unified across all tools
 */
export interface AgentFinding {
  /** Unique ID */
  id: string;
  /** Category of finding */
  category: "cost" | "health" | "zombie" | "istio" | "info";
  /** Severity level */
  severity: "low" | "medium" | "high" | "critical" | "info";
  /** Title of the finding */
  title: string;
  /** Detailed description */
  description: string;
  /** Affected resource */
  resource?: {
    kind: string;
    name: string;
    namespace?: string;
  };
  /** Suggested action */
  suggestedAction?: string;
  /** Potential impact/savings */
  impact?: string;
}

/**
 * Agent response - complete analysis result
 */
export interface AgentResponse {
  /** Whether the analysis succeeded */
  success: boolean;
  /** The intent that was processed */
  intent: AgentIntent;
  /** When the analysis started */
  startedAt: string;
  /** When the analysis completed */
  completedAt: string;
  /** Total execution time in ms */
  totalDurationMs: number;
  /** Steps executed */
  steps: AgentStep[];
  /** Executive summary - the main output */
  summary: AgentSummary;
  /** Detailed findings */
  findings: AgentFinding[];
  /** Raw data from each tool (optional) */
  rawData?: {
    snapshot?: ClusterSnapshot;
    costAnalysis?: CostAnalysisResult;
    zombieDetection?: ZombieDetectionResult;
    istioAnalysis?: IstioTrafficAnalysisResult;
  };
  /** Error if failed */
  error?: {
    code: string;
    message: string;
    step?: number;
  };
}

/**
 * Executive summary generated by the agent
 */
export interface AgentSummary {
  /** One-line headline */
  headline: string;
  /** Overall health score (0-100) */
  healthScore: number;
  /** Health status */
  healthStatus: "healthy" | "warning" | "critical";
  /** Key statistics */
  stats: {
    nodesTotal: number;
    nodesHealthy: number;
    podsTotal: number;
    podsHealthy: number;
    zombiesFound: number;
    costIssuesFound: number;
    istioIssuesFound: number;
  };
  /** Top 3 priorities */
  topPriorities: string[];
  /** Potential monthly savings */
  potentialMonthlySavings?: number;
  /** Full narrative summary */
  narrative: string;
}

// ============ Agent Configuration ============

/**
 * Agent configuration options
 */
export interface AgentConfig {
  /** Kubernetes mode */
  k8sMode: "kubeconfig" | "incluster";
  /** Enable verbose logging */
  verbose?: boolean;
  /** Timeout for entire agent run in ms */
  timeout?: number;
  /** Include raw data in response */
  includeRawData?: boolean;
  /** Logger function */
  logger?: (message: string) => void;
}

// ============ Agent Events (for streaming/progress) ============

/**
 * Agent event types for progress tracking
 */
export type AgentEventType =
  | "agent-started"
  | "step-started"
  | "step-completed"
  | "step-failed"
  | "agent-completed"
  | "agent-failed";

/**
 * Agent event for progress tracking
 */
export interface AgentEvent {
  type: AgentEventType;
  timestamp: string;
  data: {
    intent?: AgentIntent;
    step?: AgentStep;
    progress?: number; // 0-100
    message?: string;
    error?: string;
  };
}

/**
 * Event handler for agent progress
 */
export type AgentEventHandler = (event: AgentEvent) => void;
